[package]
name = "vk-group-parser"
version = "0.1.0"
authors = ["KrutNA <krutna@pm.me>"]
edition = "2018"

[dependencies]
yaml-rust = "0.4.3"
clap = "2.33.0"
serde_json = "1.0.40"
reqwest = "0.9.18"
regex = "1.1.8"
try_from = "0.3.2" 